### ISSUE TITLE
Make error (arch)

### ISSUE THREAD

**Issue by Pandiora** [ulli-kroll/mt7612u#1]
I'm getting this error when executing make on Linux Mint 18 (Ubuntu 16.04 - Kernel 4.4.0-43-gen):
```
$ sudo make
make -C tools
make[1]: Entering directory '/home/myuser/src/mt7612u/tools'
gcc -g bin2h.c -o bin2h
make[1]: Leaving directory '/home/myuser/src/mt7612u/tools'
/home/myuser/src/mt7612u/tools/bin2h
chipset = mt7612u
chipset = mt7662u
chipset = mt7632u
make ARCH= CROSS_COMPILE= -C /lib/modules/4.4.0-43-generic/build M= modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-43-generic'
Makefile:622: arch//Makefile: No such file or directory
make[1]: *** No rule to make target 'arch//Makefile'.  Stop.
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-43-generic'
Makefile:1251: recipe for target 'modules' failed
make: *** [modules] Error 2
```

On my search for a more stable driver I discovered your repo. I'm having a Devolo Wifi ac Stick (7392:c711) and I was using the mt7610u_sta (xtknight) before, which produces frequently disconnects and has a poor-performance compared to Windows 10. I think you have an idea how to easily fix this error. I've already added the device-id to rtusb_dev_id.c. Thanks for your time.

**Comment by ulli-kroll** [comment]
Standard Ubuntu/Kali-Linux whatever problem 

Please install your kernel sources.
Maybe there are other issues.

Check if 
`ls /lib/modules/$(uname -r)/build`
is valid and
`du -Ls /lib/modules/$(uname -r)/build`
around 700k, depending on the filesystem

And please.
Don't do
`sudo make `
this is dangerous

sudo is only need for install the driver, not for compile.

And you need the mt7610u driver not mt7612 one.
From the size this is some ac/an only device.

**Comment by Pandiora** [comment]
Yes, I already mentioned this device only got ac (5ghz). All mt7610 drivers I've tested either had problems with NM-Implementation or fluctuating bandwidth or random disconnects when the device were under load, like with testing the device on speedtest.net. Since your rt_usd_dev.c-File supports 7392:b711 I hoped this driver will also work for my device.

I don't have enough knowledge to know if this driver could work for my device. So if you're thinking this is impossible, please close this issue, otherwise some more information:

ls /lib/modules/$(uname -r)/build Output:
```
arch   certs   Documentation  firmware  include  ipc     Kconfig  lib       mm              net      scripts   sound  tools   usr   zfs
block  crypto  drivers        fs        init     Kbuild  kernel   Makefile  Module.symvers  samples  security  spl    ubuntu  virt
```

du -Ls /lib/modules/$(uname -r)/build:
`122660	/lib/modules/4.4.0-43-generic/build`

syslog prints a lot of errors, just a few here:
```
NetworkManager[7269]: <warn>  [1476665132.7612] device (wlan0): re-acquiring supplicant interface (#2).
wpa_supplicant[1189]: Could not set interface wlan0 flags (UP): Operation not permitted
wpa_supplicant[1189]: nl80211: Could not set interface 'wlan0' UP
wpa_supplicant[1189]: nl80211: deinit ifname=wlan0 disabled_11b_rates=0
wpa_supplicant[1189]: Could not set interface wlan0 flags (UP): Operation not permitted
wpa_supplicant[1189]: WEXT: Could not set interface 'wlan0' UP
wpa_supplicant[1189]: wlan0: Failed to initialize driver interface
kernel: [ 2182.323724] MAX_LEN_OF_MAC_TABLE can not be larger than MAX_AVAILABLE_CLIENT_WCID!!!!
kernel: [ 2182.323743] !!! rt28xx init fail !!!
```

After some reading I found out that this module normally should search for a firmware, but there is no path mentioned when I'm doing `modinfo mt7612u`. This said I don't know why rt28xx initialization fails nor where to place the needed file and which one. I also removed customizations like blacklisting rt28xx and rebooting with no success.

**Comment by ulli-kroll** [comment]
Yes I included your device 7392:b711
Some other Sitecom an/ac USB-ID only is queued up and ready for testing. This will be (hopefully) done this week.
For mt7612u and mt7610u drivers :
Both designs are on almost the same hardware, one will work as 2T2R other as 1T1R

Currently the firmware is build in as binary blobs, the
`make installfw`
is needed for a future release.
