### ISSUE TITLE
firmware mt7662

### ISSUE THREAD

**Issue by kewlfft** [ulli-kroll/mt7612u#10]
my firmware bin file is dated 20141128 more recent than yours, do you have interest in a more recent bin file?

**Comment by ulli-kroll** [comment]
Please send this as patch with proper commit (where from) and  Signed-off-by:
as normal mail, so I can test this locally.

I don't like do merge via web

And this will *not* solve the missing LED support.

**Comment by kewlfft** [comment]
understood, this makes sense
