### ISSUE TITLE
When running sudo make. compilation stop. I got it

### ISSUE THREAD

**Issue by maut** [ulli-kroll/mt7612u#14]
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.10.0-19-generic/build M= modules
make[1]: Entering directory '/usr/src/linux-headers-4.10.0-19-generic'
make[2]: *** No rule to make target 'arch/x86/entry/syscalls/syscall_32.tbl', needed by 'arch/x86/entr/syscalls/../../include/generated/asm/syscalls_32.h' Stop
arch/x86/Makefile:192: recipe for target 'archheaders' failed
make[1]: *** [archheaders] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.10.0-19-generic'
Makefile:666: recipe for target 'modules' failed
make: *** [modules] Error 

My os is ubuntu 17.04 .

**Comment by ulli-kroll** [comment]
If you got it compiled please close this issue ...

PSA
never call 
`sudo make`
