### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by klaverand** [ulli-kroll/mt7612u#17]
Hello, i have this make problem after the newest git:

make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.4.0-78-generic/build M=/home/anders/mt7612u modules
make[1]: Entering directory '/usr/src/linux-headers-4.4.0-78-generic'
  CC [M]  /home/anders/mt7612u/common/mlme.o
In file included from /home/anders/mt7612u/common/mlme.c:30:0:
/home/anders/mt7612u/common/mlme.c: In function ‘STAMlmePeriodicExec’:
/home/anders/mt7612u/include/bitfield.h:61:3: error: implicit declaration of function ‘__BUILD_BUG_ON_NOT_POWER_OF_2’ [-Werror=implicit-function-declaration]
   __BUILD_BUG_ON_NOT_POWER_OF_2((_mask) +   \
   ^
/home/anders/mt7612u/include/bitfield.h:102:3: note: in expansion of macro ‘__BF_FIELD_CHECK’
   __BF_FIELD_CHECK(_mask, _reg, 0U, "FIELD_GET: "); \
   ^
/home/anders/mt7612u/common/mlme.c:1704:9: note: in expansion of macro ‘FIELD_GET’
     if (FIELD_GET(MT_EDCA_CFG_AIFSN, Ac2Cfg) !=0xc) {
         ^
cc1: some warnings being treated as errors
scripts/Makefile.build:258: recipe for target '/home/anders/mt7612u/common/mlme.o' failed
make[2]: *** [/home/anders/mt7612u/common/mlme.o] Error 1
Makefile:1420: recipe for target '_module_/home/anders/mt7612u' failed
make[1]: *** [_module_/home/anders/mt7612u] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-78-generic'
Makefile:615: recipe for target 'modules' failed
make: *** [modules] Error 2

My hardware too old/crap - or?

**Comment by ulli-kroll** [comment]
fixed in current git.
Please check.

**Comment by klaverand** [comment]
I have checked the newest git:

In file included from /home/anders/mt7612u/common/rtusb_io.c:33:0:
/home/anders/mt7612u/common/rtusb_io.c: In function ‘APEnableTXBurstHdlr’:
/home/anders/mt7612u/include/bitfield.h:61:3: error: implicit declaration of function ‘__BUILD_BUG_ON_NOT_POWER_OF_2’ [-Werror=implicit-function-declaration]
   __BUILD_BUG_ON_NOT_POWER_OF_2((_mask) +   \
   ^
/home/anders/mt7612u/include/bitfield.h:88:3: note: in expansion of macro ‘__BF_FIELD_CHECK’
   __BF_FIELD_CHECK(_mask, 0ULL, _val, "FIELD_PREP: "); \
   ^
/home/anders/mt7612u/common/rtusb_io.c:939:13: note: in expansion of macro ‘FIELD_PREP’
   Ac0Cfg |= FIELD_PREP(MT_EDCA_CFG_TXOP, 0x20);
             ^
cc1: some warnings being treated as errors
scripts/Makefile.build:258: recipe for target '/home/anders/mt7612u/common/rtusb_io.o' failed
make[2]: *** [/home/anders/mt7612u/common/rtusb_io.o] Error 1
Makefile:1420: recipe for target '_module_/home/anders/mt7612u' failed
make[1]: *** [_module_/home/anders/mt7612u] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.4.0-78-generic'
Makefile:615: recipe for target 'modules' failed
make: *** [modules] Error 2

**Comment by klaverand** [comment]
Worked after the pull request in rtusb_io.o:

#include	"rt_config.h"
#if (LINUX_VERSION_CODE >= KERNEL_VERSION(4,9,0))
#include <linux/bitfield.h>
#else
/* Force a compilation error if a constant expression is not a power of 2 */
#define __BUILD_BUG_ON_NOT_POWER_OF_2(n)	\
	BUILD_BUG_ON(((n) & ((n) - 1)) != 0)
#define BUILD_BUG_ON_NOT_POWER_OF_2(n)			\
	BUILD_BUG_ON((n) == 0 || (((n) & ((n) - 1)) != 0))
#include <bitfield.h>
#endif
