### ISSUE TITLE
Missing parentheses?

### ISSUE THREAD

**Issue by mistotebe** [ulli-kroll/mt7612u#21]
Picked up via a compiler warning:

https://github.com/ulli-kroll/mt7612u/blob/1bbc0a6adae0ad307f6f02315a1af5b020e04448/common/cmm_data.c#L999-L1000

File history suggests the if() condition should be `(A && (B || C) && D)`, not `((A && B) || (C && D))` like it is now. So maybe the two lines should read `((TxFrameType == TX_LEGACY_FRAME) || (TxFrameType == (TX_LEGACY_FRAME | TX_NDPA_FRAME)))`?

**Comment by ulli-kroll** [comment]
The whole "TxFrameType" usage in the driver is bad ...

In most parts this in a bitfield, but here are some lines which uses this variable different ...
```
ap/ap_data.c:2252:	switch (pTxBlk->TxFrameType)
sta/rtmp_data.c:2531:	switch (pTxBlk->TxFrameType) {
```

Maybe s simple
`(TxFrameType & TX_LEGACY_FRAME)`
will work here

In the mt7610u driver, Mediatek doesn't use the bitfield logic.
strange world ;-)

**Comment by ulli-kroll** [comment]
fixed in current git
please check
