### ISSUE TITLE
rate_ctrl/alg_ags.c : Add missing square brackets. 

### ISSUE THREAD

**Issue by kprkpr** [ulli-kroll/mt7612u#4]
Hi, I think this commit is needed here too, in mt7612u and in mt7610u

https://github.com/jurobystricky/Netgear-A6210/pull/49/commits/46f1de2cc9cfefb5699417ef914bc3e4f5d55354

**Comment by ulli-kroll** [comment]
NAK

Unfortunately this code is removed due the fact that only one specific rate algorithm is enabled which doesn't use this code snipped.
