### ISSUE TITLE
USB device id for FRITZ!WLAN USB Stick AC 860

### ISSUE THREAD

**Issue by geki-yaba** [ulli-kroll/mt7612u#5]
Please add USB device id: 057C:8503 (mt7662u)

As can be seen at [0] and verified with newly bought device.

[0] https://wiki.ubuntuusers.de/WLAN/Karten/

**Comment by ulli-kroll** [comment]
Applied.

Please check current git.
Some side note, from wikidevi.com this device can support bluetooth 4 
Is this with the windows driver ??

**Comment by geki-yaba** [comment]
Perfect.

AFAIS there is no bluetooth support. Checked the INF file.

If you like I can put the driver package(INF, sys, dll, bin) on my webserver.
Maybe there are interesting parameters/binaries especially for this USB dongle?

**Comment by ulli-kroll** [comment]
Hi
there is no extra USB-ID for bluetooth
There was some USB driver (without wifi) for this device in v3.13 in drivers/staging ...
