### ISSUE TITLE
new device 0e8d:761b

### ISSUE THREAD

**Issue by kewlfft** [ulli-kroll/mt7612u#9]
Hi thanks for your work, would you be able to add this device to your list ?
ID 0e8d:761b MediaTek Inc.  mt7612u
this is the AUKEY USB WiFi Adapter AC1200 Dual Band Wireless Adapter with Detachable Antenna and USB 3.0

**Comment by ulli-kroll** [comment]
Are you serious ??
0x0e8d is Vendor ID Mediatek, and this this would mess up future USB-IDs form Mediatek.

Please post output form lsusb

**Comment by kewlfft** [comment]
the lsusb is 
Bus 003 Device 002: ID 0e8d:761b MediaTek Inc. 
the id product is 761b is it going to mess up with other IDs?

**Comment by ulli-kroll** [comment]
> the id product is 761b is it going to mess up with other IDs?

No, My problem was here AUKEY <-> Mediaktek
And AUKEY (presumedly Mediatek) uses a new Device ID and not 0x7612

queued up, Will push tomorrow

**Comment by kewlfft** [comment]
true you have a point, the ID does not match 7612
under windows it uses firmware 7662 + patch 7662 and the driver is netr28uk from Mediatek (15/7/2016).
do you want me to check something before you push it ?

**Comment by ulli-kroll** [comment]
On windows check please device attributes / properties in device-manager.
You will see the this ID in from of VEN_XXXX/PID_XXXX, I think

I have time, I'm currently fixing some problem during my local changes.

**Comment by kewlfft** [comment]
it is VID 0E8D / PID 761B
thanks for your help

**Comment by ulli-kroll** [comment]
USB ID added.
please check current git

**Comment by kewlfft** [comment]
great thanks !
